const siteBase = new URL('.', document.currentScript.src);
const LINE='https://lin.ee/zuGWiFP';
const IG='https://www.instagram.com/herecrewgym/';
let lang;try{lang=localStorage.getItem('hc-language')||'zh'}catch{lang='zh'}
let selectedDay=0,selectedCourse='all';
const pick=(zh,en)=>lang==='zh'?zh:en;
const courses=[
{id:'strength',zh:'肌力團課',en:'Strength Group',tag:['全身肌力','Full-body strength'],desc:['以深蹲、推、拉等基礎動作，循序建立全身肌力。在團體的鼓勵下，找到自己的訓練節奏。','Build full-body strength through fundamental squat, push and pull movements, with the encouragement of your crew.']},
{id:'women',zh:'女性肌力',en:'Women’s Strength',tag:['力量與自信','Strength & confidence'],desc:['在支持與鼓勵的氛圍中學習重量訓練，從動作控制到負重練習，逐步建立力量與自信。','Explore resistance training in a supportive environment, building confidence through controlled movement and progressive loading.']},
{id:'spiral',zh:'螺旋肌力',en:'Spiral Strength',tag:['旋轉與協調','Rotation & coordination'],desc:['結合旋轉、核心穩定與多方向動作，探索身體的連動，提升控制力與協調性。','Explore connected movement through rotation, core stability and multidirectional exercises that develop control and coordination.']},
{id:'sculpt',zh:'女性雕塑專班',en:'Women’s Body Sculpt',tag:['線條與力量','Shape & strength'],desc:['結合肌力與動作控制，聚焦下肢、臀部與核心，按照自己的步調累積訓練品質。','A focused strength session for the lower body, glutes and core, with attention to control and movement quality.']},
{id:'target',zh:'專項雕塑',en:'Targeted Sculpt',tag:['精準訓練','Focused training'],desc:['透過有目標的肌群訓練與細緻動作調整，建立身體感知，讓每一次練習更有方向。','Develop body awareness through focused muscle-group training and thoughtful movement adjustments.']},
{id:'beginner',zh:'初階舉重',en:'Beginner Weightlifting',tag:['技術入門','Technique foundations'],desc:['從站姿、握法與槓鈴路徑開始，學習舉重基礎。在教練引導下，把動作做穩再循序增加挑戰。','Start with stance, grip and bar path. Learn foundational weightlifting technique before gradually adding challenge.']},
{id:'intermediate',zh:'專項舉重－中階',en:'Intermediate Weightlifting',tag:['技術進階','Technical progression'],desc:['適合已有舉重基礎的學員，聚焦動作節奏、發力與技術銜接，穩定推進下一階段的練習。','For members with weightlifting foundations, focusing on timing, power and technical transitions.']},
{id:'aging',zh:'樂齡',en:'Active Aging',tag:['自在活動','Move with confidence'],desc:['透過可調整的肌力、平衡與活動度練習，支持日常活動能力，讓訓練成為生活的一部分。','Adaptable strength, balance and mobility exercises that support everyday movement and an active routine.']},
{id:'fatburn',zh:'燃脂肌力',en:'Fat-Burn Strength',tag:['肌力與體能','Strength & conditioning'],desc:['結合肌力動作與有節奏的體能練習，依個人能力調整強度，在動起來的過程中累積耐力。','Combine strength movements with paced conditioning, adjusting the challenge to your ability while developing endurance.']},
{id:'power',zh:'專項健力',en:'Powerlifting',tag:['三大項訓練','The big three'],desc:['專注深蹲、臥推與硬舉，練習穩定的動作與發力方式，讓力量進步有清晰方向。','Focus on the squat, bench press and deadlift, developing consistent technique and purposeful strength progression.']},
{id:'strongman',zh:'大力士備賽班',en:'Strongman Prep',tag:['專項力量','Event-specific strength'],desc:['以大力士項目所需的搬運、負重與全身力量為方向，建立專項動作能力與訓練節奏。','Develop event-specific carrying, loading and total-body strength for strongman-oriented training.']}
];
const coaches=[
['kari','卡爾','Karl','strength,strongman,intermediate',['力量，從每一個穩定動作開始。','Strength begins with a solid movement.'],['以清楚的動作拆解與循序練習，帶領學員建立肌力基礎，再進一步探索舉重與大力士訓練。','A clear, progressive approach to building strength foundations and exploring weightlifting and strongman training.']],
['manny','Manny','Manny','strength',['把訓練變成能持續的日常。','Make training a habit you can keep.'],['重視基本動作與訓練節奏，用容易理解的引導，陪伴學員在團課中找到適合自己的挑戰。','An approachable coaching style focused on movement fundamentals, a sustainable rhythm and the right challenge for each member.']],
['ever','Ever','Ever','women,strength,beginner',['先理解動作，再看見進步。','Understand the movement. Feel the progress.'],['透過耐心的引導與細緻觀察，陪伴學員從肌力練習走向舉重技術，累積穩定與自信。','Patient guidance and attentive movement cues to help members progress from strength foundations to weightlifting technique.']],
['zoe','Zoe','Zoe','strength',['你的步調，也是好的步調。','Your pace is a good place to start.'],['以親切而有條理的團課安排，鼓勵每位學員專注自己的動作品質，在團隊中持續進步。','Welcoming, structured group sessions that encourage each member to focus on movement quality and their own progress.']],
['rongrong','索索','Suo Suo','spiral',['讓身體連動，讓力量流動。','Connect your movement. Find your strength.'],['在螺旋肌力課程中，透過旋轉與多方向練習，引導學員探索核心穩定與全身協調。','Explore rotation and multidirectional movement, with a focus on core stability and whole-body coordination.']],
['huhu','壺壺','Hu Hu','spiral',['從控制中，找到更自在的動作。','Find freedom through control.'],['以漸進的螺旋動作練習，幫助學員感受身體連結，建立更穩定、流暢的活動方式。','Progressive spiral-movement practice that encourages body awareness, stability and smoother movement.']],
['nini','Nina','Nina','sculpt',['用力量，描繪自己的線條。','Build strength on your own terms.'],['在女性雕塑專班中，結合下肢、臀部與核心練習，重視動作感受與每一次練習的品質。','Focused lower-body, glute and core training, with an emphasis on awareness and the quality of every repetition.']],
['xuan','XUAN','XUAN','target',['專注每一次，進步就會累積。','Every focused repetition adds up.'],['透過有方向的肌群訓練與動作調整，帶領學員建立身體感知，逐步累積專項肌力。','Focused muscle-group training and considered adjustments to develop body awareness and targeted strength.']],
['zhewei','哲瑋','Zhe Wei','strength',['一起練，也一起成長。','Train together. Grow together.'],['營造有活力的團課氛圍，透過基礎肌力動作與可調整的挑戰，陪伴學員找到持續訓練的動力。','Energetic group sessions with fundamental strength movements and adaptable challenges that keep members engaged.']],
['jessie','Jessie','Jessie','aging,fatburn',['每個階段，都可以開始。','You can begin at any stage.'],['從樂齡到燃脂肌力課程，依照學員狀態安排不同節奏，讓訓練更容易融入日常生活。','An adaptable approach across active-aging and strength-conditioning sessions, helping training fit into everyday life.']],
['chris','Chris','Chris','power,beginner',['穩定的基礎，承載更大的力量。','A strong foundation carries you further.'],['聚焦健力三大項與舉重入門，透過清楚的技術提示，協助學員把每一次練習做得更穩定。','Clear technical cues for the powerlifting lifts and introductory weightlifting, with a focus on consistent practice.']]
];
const schedule=[
[['10:00','strength','kari'],['11:10','strength','kari'],['19:00','target','xuan'],['20:30','target','xuan']],
[['10:00','strength','manny'],['11:10','strength','manny'],['14:00','sculpt','nini'],['19:00','strength','zhewei'],['20:15','strength','zhewei']],
[['10:00','women','ever'],['11:10','women','ever'],['14:00','strength','ever'],['19:00','strength','zhewei'],['20:15','strength','zhewei']],
[['10:00','strength','ever'],['11:10','strength','ever'],['16:00','beginner','ever'],['19:30','beginner','ever']],
[['10:00','strength','zoe'],['11:10','strength','zoe'],['13:00','strength','zoe'],['19:00','intermediate','kari'],['20:15','intermediate','kari']],
[['10:00','spiral','rongrong'],['11:30','spiral','huhu'],['12:45','spiral','huhu'],['14:00','aging','jessie'],['15:15','fatburn','jessie'],['16:30','beginner','chris'],['18:00','beginner','chris']],
[['10:00','spiral','rongrong'],['11:30','spiral','huhu'],['13:00','power','chris'],['14:15','power','chris'],['15:30','strongman','kari'],['17:00','strength','ever']]
];
const days=[['週一','Monday'],['週二','Tuesday'],['週三','Wednesday'],['週四','Thursday'],['週五','Friday'],['週六','Saturday'],['週日','Sunday']];
const aboutEN=[
'At Here Crew, we believe strength training can mark a turning point in the way you move, feel, and live. Every session offers an opportunity to build a stronger body, discover your capabilities, and develop habits that support your physical and mental well-being.',
'Progress takes patience, consistency, and encouragement. We want to be the crew beside you throughout that journey—celebrating your achievements, supporting you through challenges, and helping you find the confidence to keep moving forward.',
'Whether you are beginning your fitness journey or working towards your next goal, Here Crew is a place to grow at your own pace and feel a sense of belonging. The strength you build here can stay with you long after each workout, bringing renewed energy and confidence to everyday life.'
];
const aboutZH=[
'在 Here Crew，我們相信重量訓練能成為人生的轉捩點，改變你活動、感受與生活的方式。每一次訓練，都是強健身體、探索自身潛能的機會，也幫助你建立支持身心健康的日常習慣。',
'進步需要耐心、持續的投入，以及身旁的鼓勵。我們希望成為一路陪伴你的夥伴——為你的每一次突破喝采，在遇到挑戰時給予支持，陪你找到繼續向前的信心。',
'無論你正準備開始健身，或正朝著下一個目標邁進，Here Crew 都是一個讓你依照自己的步調成長、找到歸屬感的地方。在這裡累積的力量，會延續到每一次訓練之外，為日常生活帶來新的活力與自信。'
];
const routes=[['/about/','關於我們','About us'],['/coaches/','教練介紹','Our crew'],['/classes/','課程介紹','Classes'],['/schedule/','課程時間表','Schedule']];
const course=id=>courses.find(c=>c.id===id);
const coach=id=>coaches.find(c=>c[0]===id);
const cn=id=>pick(coach(id)[1],coach(id)[2]);
const name=c=>pick(c.zh,c.en);
const button=(href,zh,en,kind='')=>`<a class="button ${kind}" href="${href}">${pick(zh,en)}</a>`;
function pagePath(){return ('/'+location.pathname.slice(siteBase.pathname.length)).replace(/index\.html$/,'').replace(/\/$/,'')||'/'}
function header(){return `<header class="site-header"><a class="brand" href="/" aria-label="Here Crew Home"><img src="/assets/logo.png" alt="Here Crew — Gym here, start here!"></a><nav id="navigation" aria-label="${pick('主選單','Main navigation')}">${routes.map(([url,zh,en])=>`<a href="${url}" ${pagePath()===url.replace(/\/$/,'')?'aria-current="page"':''}>${pick(zh,en)}</a>`).join('')}<a class="nav-contact" href="/contact/">${pick('聯繫我們','Get in touch')}</a></nav><div class="header-actions"><button class="language" data-action="language" aria-label="${pick('Switch to English','切換繁體中文')}">${pick('EN','中文')}</button><button class="menu-toggle" data-action="menu" aria-controls="navigation" aria-expanded="false" aria-label="${pick('開啟選單','Open menu')}"><span></span><span></span></button></div></header>`}
function footer(){return `<footer><div class="footer-top"><a href="/" class="footer-brand"><img src="/assets/logo.png" alt="Here Crew — Gym here, start here!"></a><p>${pick('你的力量，從這裡開始。','Your stronger chapter starts here.')}</p></div><div class="footer-links">${routes.map(([url,zh,en])=>`<a href="${url}">${pick(zh,en)}</a>`).join('')}<a href="${LINE}" target="_blank" rel="noopener">LINE</a><a href="${IG}" target="_blank" rel="noopener">Instagram</a></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Here Crew</span><span>TAOYUAN · TAIWAN</span><span>GYM HERE, START HERE!</span></div></footer><a class="line-float" href="${LINE}" target="_blank" rel="noopener" aria-label="${pick('透過 LINE 聯繫 Here Crew','Contact Here Crew on LINE')}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 10.5c0 4.6-5 8.1-8.4 10.1-.7.4-1 .1-.9-.5l.3-1.9C6.3 18.2 3 15 3 10.5S7 3 12 3s9 3.1 9 7.5Z" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M8 10h8M8 13h6" stroke="currentColor" stroke-width="1.5"/></svg><span>LINE</span></a>`}
function cta(){return `<section class="cta section"><span class="eyebrow">YOUR NEXT CHAPTER</span><h2>${pick('一起，開始變得更強。','Let’s get stronger.<br>Together.')}</h2><p>${pick('告訴我們你的目標，讓我們一起找到適合你的第一堂課。','Tell us what you’re working towards. We’ll help you find your first class.')}</p><div class="button-row">${button(LINE,'透過 LINE 諮詢','Chat on LINE')}${button('/schedule/','查看課程時間表','Find your class','outline')}</div></section>`}
function home(){return `<section class="hero"><video id="hero-video" autoplay muted loop playsinline preload="metadata" poster="/assets/hero.jpg" aria-label="${pick('團體健身訓練影片','Group fitness training film')}"><source src="/assets/hero.mp4" type="video/mp4"></video><div class="hero-shade"></div><div class="hero-content"><span class="eyebrow">HERE CREW · TRAINING & COMMUNITY</span><h1>${pick('你的力量，<br>從這裡開始。','A stronger you.<br>Starts here.')}</h1><p>${pick('找到你的節奏，遇見你的夥伴。<br>一起練習，一起成長。','Find your rhythm. Find your crew.<br>Train together. Grow together.')}</p><div class="button-row">${button('/classes/','探索我們的課程','Explore our classes')}${button('/about/','認識 Here Crew','Meet Here Crew','glass')}</div></div><div class="hero-foot"><span>GYM HERE, START HERE!</span><button class="video-toggle" data-action="video" aria-label="${pick('暫停影片','Pause video')}">Ⅱ</button><a href="#welcome">${pick('往下探索','DISCOVER MORE')}</a></div></section><section id="welcome" class="section welcome"><div><span class="eyebrow">MORE THAN A WORKOUT</span><h2>${pick('不只是訓練，<br>也是你的 Crew。','More than training.<br>Your kind of crew.')}</h2></div><div class="welcome-copy"><p>${pick('每一次走進 Here Crew，都是向更強大的自己靠近一步。從第一個動作到下一次突破，我們陪你找到適合自己的步調，讓力量成為生活的一部分。','Every session at Here Crew is a step towards a stronger you. From your first movement to your next breakthrough, we’re beside you as you build strength that stays with you beyond the gym.')}</p><a class="text-link" href="/about/">${pick('我們的故事','Our story')}</a></div></section><section class="section explore"><div class="section-heading"><div><span class="eyebrow">FIND YOUR MOVEMENT</span><h2>${pick('讓訓練，適合你。','Make it your kind<br>of training.')}</h2></div><a class="text-link" href="/classes/">${pick('所有課程','Explore all classes')}</a></div><div class="feature-grid">${[['01','strength','beginner'],['02','women','sculpt'],['03','spiral','aging']].map(([n,a,b])=>`<a class="feature-card" href="/classes/#${a}"><span class="feature-index">${n} / HERE CREW</span><div><h3>${name(course(a))}</h3><p>${course(a).en.toUpperCase()}</p></div><span class="feature-bottom">${pick(course(a).tag[0],course(a).tag[1])} · ${name(course(b))}</span></a>`).join('')}</div></section><section class="crew-teaser"><div class="teaser-photo"><img src="/assets/coaches/ever.webp" alt="${pick('Ever 教練示意肖像','Illustrative portrait of coach Ever')}" loading="lazy"></div><div class="teaser-copy"><span class="eyebrow">MEET YOUR CREW</span><h2>${pick('每一次進步，<br>都有夥伴同行。','Every step forward.<br>A crew beside you.')}</h2><p>${pick('找到與你合拍的教練。從肌力基礎、舉重技術，到探索身體更多可能，讓有人陪伴的訓練更有方向。','Find a coach you connect with. From strength foundations to weightlifting technique, discover what’s possible with a crew beside you.')}</p>${button('/coaches/','認識我們的教練','Meet our coaches','outline')}</div></section>${cta()}`}
function intro(kicker,title,desc=''){return `<section class="page-intro"><span class="eyebrow">${kicker}</span><h1>${title}</h1>${desc?`<p>${desc}</p>`:''}</section>`}
function about(){return `${intro('OUR STORY',pick('更強大的你，<br>從這裡開始。','A Stronger You<br>Starts Here'))}<section class="about-layout section"><div class="about-visual"><img src="/assets/hero.jpg" alt="${pick('一起參與肌力訓練','Strength training together')}" loading="lazy"><span>GYM HERE, START HERE!</span></div><div class="about-copy">${(lang==='zh'?aboutZH:aboutEN).map(p=>`<p>${p}</p>`).join('')}<strong>Gym here, start here!</strong></div></section>${cta()}`}
function coachCard(c){return `<article class="coach-card" id="${c[0]}"><div class="portrait"><img src="/assets/coaches/${c[0]}.webp" alt="${pick(c[1]+' 教練示意肖像','Illustrative portrait of '+c[2])}" loading="lazy"><span>HERE CREW</span></div><div class="coach-body"><span class="eyebrow">${pick('你的訓練夥伴','YOUR TRAINING PARTNER')}</span><h2>${pick(c[1],c[2])}</h2><p class="coach-quote">${pick(...c[4])}</p><p>${pick(...c[5])}</p><div class="tags">${c[3].split(',').map(id=>`<a href="/classes/#${id}">${name(course(id))}</a>`).join('')}</div><a class="text-link" href="/schedule/?coach=${c[0]}">${pick('查看教練課表','View coach’s classes')}</a></div></article>`}
function coachesPage(){return `${intro('MEET YOUR CREW',pick('和你一起變強的人。','The people<br>in your corner.'),pick('找到與你合拍的訓練夥伴，讓每一次進步都有支持。','Find a training partner who helps you move forward with confidence.'))}<section class="section coach-section"><div class="coach-grid">${coaches.map(coachCard).join('')}</div></section>${cta()}`}
function classesPage(){return `${intro('FIND YOUR MOVEMENT',pick('你的目標，<br>你的訓練方式。','Your goals.<br>Your way to train.'),pick('從第一次拿起重量，到下一次挑戰，找到適合你的課程。','From picking up your first weight to taking on your next challenge, find your class.'))}<section class="section classes-section"><div class="course-directory">${courses.map(c=>`<a href="#${c.id}">${name(c)}</a>`).join('')}</div><div class="class-list">${courses.map((c,i)=>`<article class="class-detail" id="${c.id}"><div class="class-number">${String(i+1).padStart(2,'0')}</div><div><span class="eyebrow">${c.en.toUpperCase()}</span><h2>${name(c)}</h2><p>${pick(...c.desc)}</p><div class="tags">${coaches.filter(x=>x[3].split(',').includes(c.id)).map(x=>`<a href="/coaches/#${x[0]}">${pick(x[1],x[2])}</a>`).join('')}</div></div><div class="class-action"><span>${pick(...c.tag)}</span>${button('/schedule/?course='+c.id,'查看上課時段','View class times','outline')}</div></article>`).join('')}</div></section>${cta()}`}
function sessionCard(s){const c=course(s[1]);return `<article class="session-card ${s[1]}"><time>${s[0]}</time><a href="/classes/#${s[1]}" class="session-title">${name(c)}</a>${lang==='zh'?`<span class="session-en">${c.en}</span>`:''}<a href="/coaches/#${s[2]}" class="session-coach">${pick('教練','Coach')} · ${cn(s[2])}</a></article>`}
function filteredSessions(d){let coachFilter=new URLSearchParams(location.search).get('coach');return schedule[d].filter(s=>(selectedCourse==='all'||s[1]===selectedCourse)&&(!coachFilter||s[2]===coachFilter))}
function schedulePage(){return `${intro('WEEKLY TRAINING',pick('把下一堂課，<br>放進你的日常。','Make room<br>for your next session.'),pick('每週固定課表 · 桃園','Weekly class schedule · Taoyuan'))}<section class="section schedule-section"><div class="schedule-toolbar"><label for="course-filter">${pick('選擇課程','Choose a class')}<select id="course-filter"><option value="all">${pick('所有課程','All classes')}</option>${courses.map(c=>`<option value="${c.id}" ${selectedCourse===c.id?'selected':''}>${name(c)}</option>`).join('')}</select></label><a class="text-link" href="/assets/timetable.png" target="_blank">${pick('查看原版課表','View original timetable')}</a></div>${new URLSearchParams(location.search).get('coach')?`<div class="filter-note">${pick('教練課表','Coach schedule')} · ${cn(new URLSearchParams(location.search).get('coach'))} <a href="/schedule/">${pick('顯示全部','Show all')}</a></div>`:''}<div class="day-tabs" role="tablist" aria-label="${pick('選擇星期','Choose a day')}">${days.map(([zh,en],i)=>`<button role="tab" id="day-${i}" aria-controls="day-panel" aria-selected="${selectedDay===i}" tabindex="${selectedDay===i?'0':'-1'}" data-day="${i}"><span>${pick(zh,en.slice(0,3))}</span><small>${pick(en.toUpperCase(),zh)}</small></button>`).join('')}</div><div class="mobile-day-label">${pick(...days[selectedDay])}</div><div class="day-panel" id="day-panel" role="tabpanel" aria-labelledby="day-${selectedDay}">${filteredSessions(selectedDay).length?filteredSessions(selectedDay).map(sessionCard).join(''):`<p class="empty-day">${pick('這天沒有符合篩選的課程，請選擇其他星期或課程。','No matching classes on this day. Choose another day or class.')}</p>`}</div><div class="week-grid">${days.map(([zh,en],i)=>`<div class="week-column"><h2>${pick(zh,en)}<small>${pick(en.toUpperCase(),zh)}</small></h2>${filteredSessions(i).length?filteredSessions(i).map(sessionCard).join(''):`<p class="week-empty">${pick('無符合課程','No matching classes')}</p>`}</div>`).join('')}</div><div class="schedule-note"><p>${pick('課程時間如有異動，請以官方公告為準。想了解課程或預約，歡迎透過 LINE 聯繫我們。','Class times may change; please refer to official announcements. Contact us on LINE for class enquiries and booking.')}</p>${button(LINE,'LINE 課程諮詢','Ask us on LINE')}</div></section>`}
function contact(){return `${intro('LET’S CONNECT',pick('你的第一步，<br>我們陪你開始。','Your first step.<br>We’re here for it.'),pick('課程選擇、訓練目標或預約諮詢，歡迎與我們聊聊。','Questions about classes, training goals or your first visit? Let’s talk.'))}<section class="section contact-grid"><div class="contact-card"><span class="eyebrow">START A CONVERSATION</span><h2>LINE</h2><p>${pick('點擊加入好友，或掃描 QR Code，與 Here Crew 聯繫。','Add us using the link or scan the QR code to connect with Here Crew.')}</p>${button(LINE,'加入 LINE 好友','Connect on LINE')}<div class="qr"><img src="/assets/line-qr.png" alt="Here Crew LINE QR Code" width="260" height="263"></div></div><div class="contact-card instagram"><span class="eyebrow">STAY IN THE LOOP</span><h2>Instagram</h2><p>@herecrewgym</p><p>${pick('看看我們的訓練日常，追蹤課程消息與 Crew 的每一步成長。','Follow our training days, class updates and the crew’s journey.')}</p>${button(IG,'追蹤 Here Crew','Follow Here Crew','outline')}<div class="instagram-word">Here<br>Crew.</div></div></section>`}
function render(){let path=pagePath(),page=path==='/about'?about:path==='/coaches'?coachesPage:path==='/classes'?classesPage:path==='/schedule'?schedulePage:path==='/contact'?contact:home;
document.documentElement.lang=lang==='zh'?'zh-Hant':'en';document.body.className=path==='/'?'home-page':'inner-page';
document.getElementById('app').innerHTML=header()+`<main id="main">${page()}</main>`+footer();
 document.querySelectorAll('[href],[src],[poster]').forEach(node=>{for(const attr of ['href','src','poster']){let value=node.getAttribute(attr);if(value?.startsWith('/')&&!value.startsWith('//')){let relative=value.slice(1);if(attr==='href'&&!relative.startsWith('assets/'))relative=relative.replace(/^(.*?)([?#].*)?$/,(_,path,suffix)=>path+(path.endsWith('/')||path===''?'index.html':'')+(suffix||''));node.setAttribute(attr,new URL(relative,siteBase).href)}}});
let title=pick('Here Crew｜你的力量，從這裡開始','Here Crew | A Stronger You Starts Here');document.title=path==='/'?title:pick(({'/about':'關於我們','/coaches':'教練介紹','/classes':'課程介紹','/schedule':'課程時間表','/contact':'聯繫我們'})[path]||'首頁',({'/about':'About Us','/coaches':'Our Coaches','/classes':'Classes','/schedule':'Schedule','/contact':'Contact Us'})[path]||'Home')+' · Here Crew';
const video=document.getElementById('hero-video');if(video){video.muted=true;video.play().catch(()=>{});if(matchMedia('(prefers-reduced-motion: reduce)').matches)video.pause();video.addEventListener('pause',()=>updateVideoButton(false));video.addEventListener('play',()=>updateVideoButton(true));updateVideoButton(!video.paused);}
if(location.hash)requestAnimationFrame(()=>document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView());
}
function updateVideoButton(playing){const b=document.querySelector('.video-toggle');if(b){b.textContent=playing?'Ⅱ':'▷';b.setAttribute('aria-label',playing?pick('暫停影片','Pause video'):pick('播放影片','Play video'))}}
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]');if(action){if(action.dataset.action==='language'){const y=scrollY;lang=lang==='zh'?'en':'zh';try{localStorage.setItem('hc-language',lang)}catch{}render();scrollTo(0,y)}if(action.dataset.action==='menu'){const open=document.body.classList.toggle('menu-open');action.setAttribute('aria-expanded',String(open));action.setAttribute('aria-label',open?pick('關閉選單','Close menu'):pick('開啟選單','Open menu'))}if(action.dataset.action==='video'){const v=document.getElementById('hero-video');v.paused?v.play().catch(()=>{}):v.pause()}}
const day=e.target.closest('[data-day]');if(day){selectedDay=+day.dataset.day;const y=scrollY;render();scrollTo(0,y);document.getElementById('day-'+selectedDay)?.focus({preventScroll:true})}});
document.addEventListener('change',e=>{if(e.target.id==='course-filter'){selectedCourse=e.target.value;const y=scrollY;render();scrollTo(0,y);document.getElementById('course-filter').focus({preventScroll:true})}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('menu-open')){document.body.classList.remove('menu-open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');document.querySelector('.menu-toggle').focus()}if(e.target.matches('[data-day]')&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();selectedDay=e.key==='Home'?0:e.key==='End'?6:(selectedDay+(e.key==='ArrowRight'?1:6))%7;const y=scrollY;render();scrollTo(0,y);document.getElementById('day-'+selectedDay).focus({preventScroll:true})}});
const initialCourse=new URLSearchParams(location.search).get('course');if(courses.some(c=>c.id===initialCourse))selectedCourse=initialCourse;
// Validate unknown coach values without treating external input as markup.
if(new URLSearchParams(location.search).has('coach')&&!coach(new URLSearchParams(location.search).get('coach'))){history.replaceState(null,'',location.pathname)}
render();
